package main

import (
	"github.com/gramework/gramework"
)

func main() {
	// Create app
	app := gramework.New()

	// Initialize the app
	//
	// Initializes required email address for autogenerated certificates etc.
	setup(app)

	// Setup gramework.win handlers
	win(app)

	// Setup share.gramework.win handlers
	share(app)

	// run the app
	//
	// NOTE: implemented in environment-specific way
	// now we support running in prod and (defualt) dev mode
	// and compiling under Go and (not released yet) Goodlang
	// 0.7.0+ (which provides "bare" and "infrastructure"
	// packages)
	run(app)
}
